services:
  boilerplate-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9090
      - ConnectionStrings__DefaultConnection=Host=db-server;Port=5432;Database=HeroDb;Username=app_user;Password=myHardCoreDevDb123
    ports:
      - "9090:9090"
    networks:
      - localdev